# Generated by Django 3.2.3 on 2021-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210529_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='ordereditems',
            field=models.CharField(max_length=30),
        ),
    ]
