# Generated by Django 3.2.3 on 2021-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='waiting for confirmation', max_length=10),
            preserve_default=False,
        ),
    ]
