# Generated by Django 3.2.3 on 2021-07-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='usermail',
            field=models.CharField(default='singhswapnil507@gmail.com', max_length=25),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='Waiting for confirmation', max_length=10),
        ),
    ]
